package tr.kontas.splitr.consumer.store;

/**
 * Strategy interface for managing the idempotency of distributed queries.
 * <p>
 * This store prevents the redundant execution of identical queries by caching
 * the results of previously processed correlation IDs.
 * </p>
 *
 * @author BurakKontas
 * @version 1.0.0
 */
public interface IdempotencyStore {

    /**
     * Checks if a specific query correlation ID has already been processed.
     *
     * @param id The unique correlation ID of the query.
     * @return {@code true} if the result exists in the store, {@code false} otherwise.
     */
    boolean contains(String id);

    /**
     * Retrieves the cached response for a given correlation ID.
     *
     * @param id The unique correlation ID.
     * @return The {@link Object} associated with the ID, or {@code null} if not found.
     */
    Object get(String id);

    /**
     * Persists a query result to the store with default TTL.
     *
     * @param id The unique correlation ID.
     * @param r  The response generated by a handler.
     */
    void put(String id, Object r);

    /**
     * Persists a query result to the store with custom TTL.
     *
     * @param id    The unique correlation ID.
     * @param r     The response generated by a handler.
     * @param ttlMs Time-to-live in milliseconds for this entry.
     */
    default void put(String id, Object r, long ttlMs) {
        put(id, r); // Fallback to default TTL
    }

    /**
     * Removes expired entries from the store.
     * <p>
     * Implementations should use this method to prevent memory leaks
     * by periodically cleaning up expired entries.
     * </p>
     *
     * @return The number of entries removed.
     */
    default int cleanup() {
        return 0; // No-op by default
    }

    /**
     * Removes a specific entry from the store.
     *
     * @param id The unique correlation ID to remove.
     * @return {@code true} if the entry was removed, {@code false} if it didn't exist.
     */
    default boolean remove(String id) {
        return false; // No-op by default
    }

    /**
     * Clears all entries from the store.
     * <p>
     * Useful for testing or administrative operations.
     * </p>
     */
    default void clear() {
        // No-op by default
    }

    /**
     * Returns the current number of entries in the store.
     *
     * @return The size of the store.
     */
    default int size() {
        return 0; // No-op by default
    }

    /**
     * Checks if the store is healthy and operating within acceptable limits.
     * <p>
     * Implementations can use this to determine if the store is near capacity
     * or experiencing issues.
     * </p>
     *
     * @return {@code true} if healthy, {@code false} otherwise.
     */
    default boolean isHealthy() {
        return true; // Healthy by default
    }

    /**
     * Gracefully shuts down the store, releasing any resources.
     * <p>
     * This should be called during application shutdown to prevent resource leaks.
     * </p>
     */
    default void shutdown() {
        // No-op by default
    }
}